---
# tasks file for first-add-non-root-user
- name: Create the ansible user
  user:
    name: ansible
    append: yes
    state: present
    create_home: yes
    shell: /bin/bash

- name: Allow ansible to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    line: 'ansible ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Setup authorized keys for ansible user
  authorized_key: user=ansible key="{{item}}"
  with_file:
    - /home/ansible/.ssh/id_rsa.pub