- name: Install docker on servers
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3  
  vars_files:
    - group_vars/default.yml
  tasks:
    - name: Ensure group "docker" exists with correct gid
      group:
        name: docker
        state: present

    - name: Adding user {{ user }}
      user: 
        name: ansible
        group: docker 
        shell: /bin/bash 
        append: yes        

    - name: Reboot host and wait for it to restart
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami        
