- name: Deploy a web application
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3  
  vars_files:
    - group_vars/db.yml
  tasks:
  - name: Install python-apt
    apt:
      name:
        - python-pymysql
        - python3-pymysql
        - python-apt
        - python3-apt
    state: latest
    
  - name: Install aptitude using apt
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

  - name: Install required system packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'python', 'python-setuptools', 'curl', 'python-dev', 'build-essential', 'python-pip', 'python-mysqldb']
      
  - name: Install MySQL database
    apt: name={{ item }} state=latest force=yes
    loop: ['mysql-server' ,  'mysql-client']

  - name: Start MySQL Server
    service:
      name: mysql
      state: started
      enabled: yes

  - name: Create Application database
    mysql_db: name={{ db_name }} state=present

  - name: Create user for database
    mysql_user:
      name: "{{ db_user }}"
      password: "{{ db_user_pass }}"
      priv: '*.*:ALL'
      state: present
      host: '%'

  - name: Install python Dependencies
    pip:
      name: "{{ item }}"
      state: present
    loop: [ 'flask' , 'flask-mysql']
    
  - name: Copy source code
    copy: src=app.py dest=/opt/app.py

  - name: Start webserver
    shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &
