- name: Deploy a web application
  hosts: all
  tasks:
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600  
  # - name: Install all required dependencies
  #   apt:
  #     name: "{{ item }}"
  #     state: latest
  #   which_items:
  #     - python
  #     - python-setuptools
  #     - python-dev
  #     - build-essential
  #     - python-pip
  #     - python-mysqldb

  - include: tasks/deploy-db.yml
  - include: tasks/deploy-web.yml

