- name: Deploy a web application
  hosts: all
  tasks:
  - name: Install aptitude using apt
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

  - name: Install required system packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'python', 'python-setuptools', 'curl', 'python-dev', 'build-essential', 'python-pip', 'python-mysqldb']
      
  - include: tasks/deploy-db.yml
  - include: tasks/deploy-web.yml

