- name: Deploy a web application
  hosts: all
  tasks:
  - name: Install aptitude using apt
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

  - name: Install required system packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'python', 'python-setuptools', 'curl', 'python-dev', 'build-essential', 'python-pip', 'python-mysqldb']
      
  - name: Install MySQL database
    apt: name={{ item }} state=installed force=yes
    which_items:
      - mysql_server
      - mysql_client

  - name: Start MySQL Server
    service:
      name: mysql
      state: started
      enabled: yes

  - name: Create Application database
    mysql_db: name={{ db_name }} state=present

  - name: Create user for database
    mysql_user:
      name: "{{ db_user }}"
      password: "{{ db_user_pass }}"
      priv: '*.*:ALL'
      state: present
      host: '%'
  - include: tasks/deploy-web.yml

