- name: Deploy a web application
  hosts: all
  tasks:
  tasks:
  - name: Install aptitude using apt
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

  - name: Install required system packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
  # - name: Install required system packages
  #   apt: name={{ item }} state=latest update_cache=yes
  #   which_items:
  #     - python
  #     - python-setuptools
  #     - python-dev
  #     - build-essential
  #     - python-pip
  #     - python-mysqldb
      
  - include: tasks/deploy-db.yml
  - include: tasks/deploy-web.yml

