- name: Deploy a web application
  hosts: all
  tasks:
    - name: Install all required dependencies
      apt: 
        name: {{ item }} 
        state: latest 
        forece: yes
      which_items:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip
        - python-mysqldb

    - include: tasks/deploy-db.yml
    - include: tasks/deploy-web.yml

