- name: Install python Dependencies
  pip:
    name: "{{ item }}"
    state: present
  which_items:
    - flask
    - flask-mysql
  

- name: Copy source code
  copy: src=app.py dest=/opt/app.py

- name: Start webserver
  shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &